<a href="https://colab.research.google.com/github/kimdonggyu2008/SKT_FLY_AI_6/blob/main/12_NN_LR_SAMPLE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#뉴럴 네트워크(회귀)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
import keras

In [7]:
x_train=np.array([1.,2.,3.,4.,5.,6.])
y_train=np.array([9.,12.,15.,18.,21.,24])

#사이킷런 선형회귀

In [8]:
x_train=x_train.reshape(-1,1)
x_train

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [9]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [10]:
lr.coef_, lr.intercept_

(array([3.]), 5.999999999999998)

#테스트

In [15]:
lr.predict([[10.]])

array([36.])

#뉴럴 네트워크 사용

In [17]:
from keras import layers

model=keras.Sequential([
    layers.Input(shape=(1,)),
    layers.Dense(units=1)
])

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

# 컴파일
- 손실함수, 경사하강법(옵티마이저)
- 매트릭스(평가지표)

In [19]:
model.compile(
    optimizer='sgd',
    loss='mse',
    metrics=['mae']
)

In [20]:
epochs=100

model.fit( #학습을 통해 가중치, 바이어스 결정됨
    x_train,y_train,
    epochs=epochs,
    batch_size=6,
    verbose=1.
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 599ms/step - loss: 365.4978 - mae: 18.1720
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - loss: 171.6308 - mae: 12.6464
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 81.8854 - mae: 8.8862
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 40.3307 - mae: 6.3270
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 21.0802 - mae: 4.5850
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 12.1529 - mae: 3.3988
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 8.0036 - mae: 2.5908
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 6.0659 - mae: 2.0401
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 5.1518 - mae: 1.8626
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 4.7117 - mae: 1.7592
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4.4910 - mae: 1.7568
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 4.3721 - mae: 1.7531
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━

In [24]:
model.get_weights()

[array([[3.7971747]], dtype=float32), array([2.587137], dtype=float32)]

In [26]:
model.predict(np.array([[10]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[40.558884]], dtype=float32)